### ISSUE TITLE
Componente de edição dados de mapeamento.

### ISSUE THREAD

**Issue by raphera** [Tamandutech/LineFollower_CCenter_Code#1]

**Comment by Matheus-de-Sousa** [comment]
Criei o layout do mapeamento no Vue e implementei a edição do mapeamento na dashboard, porém falta otimizar algumas coisas, como o tempo que leva para enviar o mapeamento e salvá-lo na flash.
![image](https://user-images.githubusercontent.com/47544738/172962446-67aa8517-a304-4cf3-8c7e-bf3cdd900971.png)
![image](https://user-images.githubusercontent.com/47544738/172962709-e127b20f-d3f8-41eb-a08a-51234b313acb.png)
